client_db sql added
tokuchar/shop-sandbox pull request #21
Opened 2020-08-19 22:20 UTC by AnnLas

;_____________________;

![client_db_schema](https://user-images.githubusercontent.com/30300798/90695506-df644780-e27a-11ea-8bde-c2f2c4a67c87.PNG)

2020-08-20 08:35 UTC, AnnLas commented
resolve #4

2020-08-20 10:59 UTC, AnnLas commented
![image](https://user-images.githubusercontent.com/30300798/90762236-0192af80-e2e5-11ea-827e-7fe006081f3d.png)

new schema

2020-08-25 08:12 UTC, tokuchar approved these changes

2020-08-25 08:24 UTC, pomaraqcz requested changes
user - company one to many a powinno byc one to one

2020-08-25 08:25 UTC, AnnLas commented
nie

2020-08-25 08:26 UTC, pomaraqcz approved these changes

2020-08-25 08:27 UTC, merged

2020-08-25 08:27 UTC, AnnLas commented
to później zrobię jakieś śmieć-dane do tego